version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: drails
      POSTGRES_USER: drails_user
      POSTGRES_PASSWORD: secret!
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_NAME: drails
      DB_USERNAME: drails_user
      DB_PASSWORD: secret!
    depends_on:
      - db